.TH SUSPICIOUS-TOOLS 7 "2024-01-13" "arthurbacci's suspicious-tools"
.SH DESCRIPTION
Collection of utilities trying to comply with the POSIX standars (version
depends on the program). Most are written in C90 and try to be simple.
.SH PROGRAMS
.TP
errno(1)
.TP
timeout(1)
.TP
watch(1)
.SH REPORTING BUGS
Please open an issue at https://github.com/arthurbacci/suspicious-tools or send
an email to arthurbacci at protonmail.com.
