.TH ERRNO 1 "2024-01-13" "arthurbacci's suspicious-tools"
.SH NAME
errno \- display the available errno codes
.SH SYNOPSIS
\fBerrno\fR [\fB-S\fR] [\fIname or number\fR]
.SH DESCRIPTION
.B errno
If no arguments are passed, displays the errno codes defined in the system in
which it was compiled. If a number is passed to it, it displays the errno
name(s) associated with it. If a name is passed, it displays it's information.
Output is in a form similar to \fBEAGAIN 11 Resource temporarily
unavailable\fR.
.SH OPTIONS
.TP
\fB-S\fR
Display the message in all locales.
.SH NOTES
Differently from moreutils' implementation, there are no options for searching.
Instead, you're supposed to use \fBerrno | grep \fIword\fR.
.SH REPORTING BUGS
Please open an issue at https://github.com/arthurbacci/suspicious-tools or send
an email to arthurbacci@protonmail.com.
